version: '2'
services:
  app:
    image: "busybox:latest"
    volumes:
      - .:/var/lib/php/tyoshii/sample
  php:
    build: ./docker/php
    image: sample-php
    volumes_from:
      - app
    ports:
      - 8081:80
  yarn:
    build: ./docker/yarn
    image: sample-yarn
    volumes_from:
      - app
    ports:
      - 8082:8082
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: rental
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
