=head1 fetch google recommend calendar

=head2 SYNOPSYS

    1. Install cpanm

    2. Install required cpan module. following:
        $ cpanm WWW::Mechanize
        $ cpanm JSON::XS
        $ cpanm YAML        

    3. Set google account loging information.
        $ cat .config.pl

        return +{
            Email  => 'hogehoge@mail.com',
            Passwd => '**************',
        };

    4. Execute script
        $ perl fetch.pl

=head2 DESCRIPTION

googleオススメカレンダーをfetchして、scraper for ruby が利用する、scrape_categories.yml形式で、情報を出力します。

現在、全てfetchするようになっていて、３０分ほど取得に時間がかかります。
オプションをとれるように、変更することはできます。

=cut
