=head1 fetch google recommend calender

=head2 SYNOPSYS

    $ perl fetch.pl

    required modules
        WWW::Mechanaize
        JSON::XS

=head2 DESCRIPTION

create 'category/sports.json'
create 'league/league:XXXXXXXX.json'

Before execute, create .config.pl following:

    return +{
        Email => 'hogehoge@gmail.com',
        Passwd => '**************',
    };
